### ISSUE TITLE
only sources are published

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt-bintray#74] opened 2015-09-27 20:32 UTC
here is the project https://github.com/OlegYch/sigar
after sigar/bintrayRelease i only see a jar with sources at https://bintray.com/olegych/maven/sigar-olegych/1.7.0/view#files
publishLocal correctly publishes all artifacts
as a side note sigar/publish fails with "Provided artifact path does not comply with Maven's convention"

**Comment by 2m** [comment] 2018-03-27 11:02
Seems that an ivy artifact was being released to a maven repository. There has been development in this plugin functionality since, which might have rendered this obsolete. Closing the ticket. Feel free to open a new one if the problem is still there.

**Closed by 2m** 2018-03-27 11:02 UTC
