### ISSUE TITLE
[error] (*:bintrayRelease): java.lang.NoSuchMethod

### ISSUE THREAD

**Issue by kondaurovDev** [sbt/sbt-bintray#118] opened 2017-06-27 12:38 UTC
I have
plugins.sbt
addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.4.0")

I run publish

```
> publish
[info] Wrote /home/alex/Projects/kondaurov-json/pager/target/scala-2.11/pager_2.11-1.0.0.pom
[info] :: delivering :: com.github.kondaurovdev#pager_2.11;1.0.0 :: 1.0.0 :: release :: Tue Jun 27 15:30:07 MSK 2017
[info]  delivering ivy file to /home/alex/Projects/kondaurov-json/pager/target/scala-2.11/ivy-1.0.0.xml
[info]  published pager_2.11 to https://api.bintray.com/maven/kondaurovdev/maven/maven/com/github/kondaurovdev/pager_2.11/1.0.0/pager_2.11-1.0.0.pom
[info]  published pager_2.11 to https://api.bintray.com/maven/kondaurovdev/maven/maven/com/github/kondaurovdev/pager_2.11/1.0.0/pager_2.11-1.0.0.jar
[info]  published pager_2.11 to https://api.bintray.com/maven/kondaurovdev/maven/maven/com/github/kondaurovdev/pager_2.11/1.0.0/pager_2.11-1.0.0-sources.jar
[trace] Stack trace suppressed: run last *:bintrayRelease for the full output.
[error] (*:bintrayRelease) java.lang.NoSuchMethodError: org.json4s.Formats.emptyValueStrategy()Lorg/json4s/prefs/EmptyValueStrategy;
[error] Total time: 55 s, completed Jun 27, 2017 3:31:01 PM
> last *:bintrayRelease
java.lang.NoSuchMethodError: org.json4s.Formats.emptyValueStrategy()Lorg/json4s/prefs/EmptyValueStrategy;
        at org.json4s.native.JsonMethods$class.render(JsonMethods.scala:29)
        at org.json4s.native.JsonMethods$.render(JsonMethods.scala:62)
        at bintry.Methods$json$.str(Methods.scala:19)
        at bintry.Methods$Repo$Package$Version$Attrs$.update(Methods.scala:147)
        at bintray.BintrayRepo$$anonfun$publishVersionAttributes$1.apply(BintrayRepo.scala:23)
        at bintray.BintrayRepo$$anonfun$publishVersionAttributes$1.apply(BintrayRepo.scala:23)
        at bintray.Bintray$await$.ready(Bintray.scala:119)
        at bintray.BintrayRepo.publishVersionAttributes(BintrayRepo.scala:22)
        at bintray.BintrayPlugin$$anonfun$publishVersionAttributesTask$1.apply(BintrayPlugin.scala:149)
        at bintray.BintrayPlugin$$anonfun$publishVersionAttributesTask$1.apply(BintrayPlugin.scala:147)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[error] (*:bintrayRelease) java.lang.NoSuchMethodError: org.json4s.Formats.emptyValueStrategy()Lorg/json4s/prefs/EmptyValueStrategy;

```

**Comment by andyglow** [comment] 2017-06-27 17:35
+1

**Comment by jvican** [comment] 2017-06-27 17:36
Fix is here: https://github.com/sbt/sbt-bintray/pull/108. Has to be merged and requires release of bintry.

**Comment by dwijnand** [comment] 2017-06-28 12:45
Yeah, dupe of #104.

**Closed by dwijnand** 2017-06-28 12:45 UTC
