### ISSUE TITLE
Only warn about missing credentials if publishing

### ISSUE THREAD

**Issue by erip** [sbt/sbt-bintray#120] opened 2017-06-27 23:14 UTC
To be done after #114.

Given no credential file, any time something depending on sbt-bintray is compiled, a huge number of "warnings" (i.e., lines printed to stdout) appear:

    Missing bintray credentials /Users/user/.bintray/.credentials. Some bintray features depend on this.

This should only appear when publishing.

**Comment by dwijnand** [comment] 2017-06-28 12:47
Dupe of #88.

**Closed by dwijnand** 2017-06-28 12:47 UTC
