### ISSUE TITLE
Is Bintray-Sbt working behind a proxy?

### ISSUE THREAD

**Issue by giena** [sbt/sbt-bintray#80] opened 2016-02-09 10:36 UTC
Hi, 

I'm trying to publish on bintray using sbt bintray. I get this error. I've configured my proxy as usual (JAVA_OPTS and SBT_OPTS). Have you got an idea?

[info]  delivering ivy file to /home/giena/devt/work/scala/CCP/scaerospike/target/scala-2.11/ivy-1.2.2-SNAPSHOT.xml
java.util.concurrent.ExecutionException: java.net.ConnectException: connection timed out: api.bintray.com/75.126.118.184:443 to https://api.bintray.com/maven/worldline-messaging-bintray/maven/scaerospike/com/tapad/scaerospike/scaerospike_2.11/1.2.2-SNAPSHOT/scaerospike_2.11-1.2.2-SNAPSHOT.pom;publish=1;override=0
    at com.ning.http.client.providers.netty.NettyResponseFuture.abort(NettyResponseFuture.java:342)
    at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:107)
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
    at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:140)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out: api.bintray.com/75.126.118.184:443 to https://api.bintray.com/maven/worldline-messaging-bintray/maven/scaerospike/com/tapad/scaerospike/scaerospike_2.11/1.2.2-SNAPSHOT/scaerospike_2.11-1.2.2-SNAPSHOT.pom;publish=1;override=0
    at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
    at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:140)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: api.bintray.com/75.126.118.184:443
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:137)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error](*:publish) java.util.concurrent.ExecutionException: java.net.ConnectException: connection timed out: api.bintray.com/75.126.118.184:443 to https://api.bintray.com/maven/worldline-messaging-bintray/maven/scaerospike/com/tapad/scaerospike/scaerospike_2.11/1.2.2-SNAPSHOT/scaerospike_2.11-1.2.2-SNAPSHOT.pom;publish=1;override=0

**Comment by agilestevesmith** [comment] 2016-04-11 15:00
Hi I might have this issue as well, is it possible bintray-sbt is discarding SBT_OPTS before it establishes a connection to Bintray?

**Comment by agilestevesmith** [comment] 2016-04-12 13:02
Hi @softprops, after some investigation it appears the problem is due to bintray-sbt not specifying proxy support when using https://github.com/dispatch/dispatch 

@giena

**Comment by IPO-srh-sloan** [comment] 2016-08-25 14:03
We've also got an issue with this - we are behind a proxy so this means we can't use the bintray-sbt plugin. Are there any plans to fix this @softprops ? Thanks.

**Comment by jvican** [comment] 2017-05-06 16:43
Hello guys. No, there are no plans. But if you want to step up and implement it, it should not be difficult. I'm here to help out if you get stuck.

**Comment by bogdanromanx** [comment] 2018-01-14 23:56
As a workaround you can directly configure the underlying client by passing the following properties when running sbt:
```
-Dcom.ning.http.client.AsyncHttpClientConfig.useProxyProperties=true \ 
-Dhttp.proxyHost=<HOST> \ 
-Dhttp.proxyPort=<PORT>
```
See: https://stackoverflow.com/a/14456852

**Comment by 2m** [comment] 2018-03-27 11:06
Closing as there is a workaround. If the workaround is troublesome, please open a new ticket where we can work on implementing a proper fix.

**Closed by 2m** 2018-03-27 11:06 UTC
