### ISSUE TITLE
RuntimeException: was not able to find or create a package for ...

### ISSUE THREAD

**Issue by luchesar** [sbt/sbt-bintray#32] opened 2014-08-18 13:48 UTC
I am trying to publish my project to bintray following the instruction to the letter from: https://github.com/softprops/bintray-sbt/blob/0.1.2/README.md

I keep getting:

```
java.lang.RuntimeException: was not able to find or create a package for luchesar in repo maven named sbt.SettingKey$$anon$4@6028e736
    at scala.sys.package$.error(package.scala:27)
    at bintray.Plugin$$anonfun$ensurePackageTask$1.apply(Plugin.scala:72)
    at bintray.Plugin$$anonfun$ensurePackageTask$1.apply(Plugin.scala:45)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
```

Sounds really confusing to me and looks like nobody else has experience anything like that... Any suggestions?

The project is using build.sbt and the code is still not published to github. The github project in question is https://github.com/luchesar/vehicles-online . The current version there uses Build.scala and has an other problem when trying to publish with bintray-sbt plugin. The problem is:
`[error] (*:publish) error uploading to https://api.bintray.com/maven/luchesar/maven/maven/dvla/vehicles-online_2.10/1.0-SNAPSHOT/vehicles-online_2.10-1.0-SNAPSHOT.pom: {"message":"Provided artifact path does not comply with Maven's convention"}`

**Comment by 2m** [comment] 2018-03-27 10:45
Duplicate of https://github.com/sbt/sbt-bintray/issues/32

**Closed by 2m** 2018-03-27 10:45 UTC
