### ISSUE TITLE
sbt-native-package and .deb files

### ISSUE THREAD

**Issue by sumdog** [sbt/sbt-bintray#27] opened 2014-06-26 04:30 UTC
Cool plugin. I'm having some trouble with the sbt-native-packager though. I'm trying to publish my .deb file (sbt debian:package-bin), located in /target/[name]-[ver].deb. 

I've used a couple of variations of the configuration below, but it seems to always want to publish as me (not the organization I have specified, "bigsense") and it always published the .jar files.

Is there a way to publish the .deb files to bigsense/trusty (a debian repo) on bintray?

```
import _root_.sbt.Keys._
import com.typesafe.sbt.SbtNativePackager.packageArchetype
import com.typesafe.sbt.SbtNativePackager.Universal
import NativePackagerKeys._

name := "bigsense"

version := "0.2alpha"

scalaVersion := "2.10.3"

resolvers += "couchbase" at "http://files.couchbase.com/maven2/"

libraryDependencies ++= Seq(
    "org.springframework" % "spring-beans" % "3.0.5.RELEASE",
    "org.springframework" % "spring-context" % "3.0.5.RELEASE",
    "org.springframework" % "spring-core" % "3.0.5.RELEASE",
    "org.springframework" % "spring-expression" % "3.0.5.RELEASE",
    "org.springframework" % "spring-asm" % "3.0.5.RELEASE",
    "org.springframework" % "spring-aop" % "3.0.5.RELEASE",
    "cglib" % "cglib" % "2.2.2",
    "aopalliance" % "aopalliance" % "1.0",
    "commons-logging" % "commons-logging" % "1.1.1",
    "commons-codec" % "commons-codec" % "1.6",
    "commons-io" % "commons-io" % "2.4",
    "net.sourceforge.jtds" % "jtds" % "1.2.4",
    "com.jolbox" % "bonecp" % "0.7.1.RELEASE",
    "org.slf4j" % "slf4j-log4j12" % "1.6.1",
    "org.scalaj" %% "scalaj-collection" % "1.5",
    "bouncycastle" % "bcprov-jdk15" % "140",
    "postgresql" % "postgresql" % "9.1-901.jdbc4",
    "mysql" % "mysql-connector-java" % "5.1.30",
    "org.eclipse.jetty" % "jetty-server" % "9.1.4.v20140401",
    "org.eclipse.jetty" % "jetty-servlet" % "9.1.4.v20140401",
    "org.eclipse.jetty" % "jetty-webapp" % "9.1.4.v20140401",
    "org.rogach" %% "scallop" % "0.9.5",
    "org.apache.tomcat.embed" % "tomcat-embed-core"         % "7.0.53" ,
    "org.apache.tomcat.embed" % "tomcat-embed-logging-juli" % "7.0.53" ,
    "org.apache.tomcat.embed" % "tomcat-embed-jasper"       % "7.0.53" ,  //JSP (remove?)
    "org.apache.commons" % "commons-compress" % "1.6"
)

licenses := Seq("GPL-3.0" -> url("http://www.gnu.org/licenses/gpl-3.0.html"))

//publishing

bintray.Keys.bintrayOrganization in bintray.Keys.bintray := Some("bigsense")

bintray.Keys.repository in bintray.Keys.bintray := "trusty"

seq(bintrayPublishSettings:_*)

//packaging

packageArchetype.java_server

packageDescription := "web service designed for consuming and reporting data from sensor networks"

packageSummary := "BigSense is a web service designed to process and report data from sensor networks. (http://bigsense.io)"

maintainer := "Sumit Khanna<sumit@penguindreams.org>"

fork in run := true

Twirl.settings
```

**Comment by aparkinson** [comment] 2015-01-10 10:08
I have got a little further down this route using the following

```
bintrayPublishSettings

repository in bintray := "my-repo"

bintrayOrganization in bintray := Some("hindsightsoftware")

SettingsHelper.makeDeploymentSettings(Debian, packageBin in Debian, "deb")

publish <<= publish.dependsOn(publish in config("debian"))
```

Unfortunately publishing fails after uploading the file because Bintray requires the Debian distribution, component and architecture: https://bintray.com/docs/api/#_debian_upload

**Comment by softprops** [comment] 2015-05-08 01:49
going to look more into this in upcoming releases

**Comment by 2m** [comment] 2018-03-27 10:30
`sbt-bintray` is now an auto-plugin and the setting application order is therefore fixed. As for the `deb` publishing, `sbt-native-packager` has evolved ever since and this needs to be tried again to see if the problem is still there. Closing this for now.

**Closed by 2m** 2018-03-27 10:30 UTC
