### ISSUE TITLE
Cannot Publish Multiple Modules to Same Package

### ISSUE THREAD

**Issue by jrduncans** [sbt/sbt-bintray#147] opened 2018-03-07 21:48 UTC
I've had to let each sub-module create and publish to their own Bintray package, because (at least on initial upload), having them set to the same Bintray package would error saying it could not find or update the package.

**Comment by jvican** [comment] 2018-03-07 22:01
You were probably setting it up wrong. I've recently set this up in a project with the latest master version and it worked. Are you sure you overrode the bintray package name at the *project scope* sbt level?

**Comment by eed3si9n** [comment] 2018-03-07 22:07
Here's houserules plugin we use to transfer bintrayPackage key to build level - https://github.com/sbt/sbt-houserules/blob/v0.3.5/src/main/scala/sbt/houserules/BintraySettingPlugin.scala

With that you can set bintrayPackage once in ThisBuild scoping.

**Comment by jrduncans** [comment] 2018-03-09 19:48
@eed3si9n can you reopen this? I don't believe my problem is with setting the `bintrayPackage`, it's that doing so causes my release+publish to fail. It publishes one module successfully (see https://bintray.com/jrduncans/maven/testsbtmultiprojectbintray#files/com%2Fstephenduncanjr%2Ftestsbtmultiprojectbintray-extra_2.12%2F0.1), and then fails on the second one.

Here's a sample project: https://github.com/jrduncans/testsbtmultiprojectbintra

Here's the release output:

> sbt release                                                                                                                                                                                                                                                                                            Fri Mar  9 11:42:25 2018
[info] Loading global plugins from /Users/Shared/Development/NikeBuild/.sbt/0.13/plugins
[info] Loading project definition from /Users/sdunc4/tmp/testsbtmultiprojectbintray/project
[info] Set current project to testsbtmultiprojectbintray (in build file:/Users/sdunc4/tmp/testsbtmultiprojectbintray/)
[info] Starting release process off commit: 6daceb8d823c875559b2b2a9ee6af75dd4ba5ea5
[info] Checking remote [origin] ...
Release version [0.1] :
Next version [0.2-SNAPSHOT] :
[success] Total time: 0 s, completed Mar 9, 2018 11:42:39 AM
[info] Updating {file:/Users/sdunc4/tmp/testsbtmultiprojectbintray/}testsbtmultiprojectbintray-extra...
[info] Updating {file:/Users/sdunc4/tmp/testsbtmultiprojectbintray/}testsbtmultiprojectbintray...
[info] Updating {file:/Users/sdunc4/tmp/testsbtmultiprojectbintray/}testsbtmultiprojectbintray-core...
[info] Resolving jline#jline;2.14.5 ...
[info] Done updating.
[info] Resolving org.scala-lang#scala-reflect;2.12.4 ...
[info] Compiling 1 Scala source to /Users/sdunc4/tmp/testsbtmultiprojectbintray/extra/target/scala-2.12/classes...
[info] Resolving jline#jline;2.14.5 ...
[info] Done updating.
[info] Resolving jline#jline;2.14.5 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/sdunc4/tmp/testsbtmultiprojectbintray/core/target/scala-2.12/classes...
[success] Total time: 4 s, completed Mar 9, 2018 11:42:43 AM
[info] Setting version to '0.1'.
[info] Reapplying settings...
[info] Set current project to testsbtmultiprojectbintray (in build file:/Users/sdunc4/tmp/testsbtmultiprojectbintray/)
[info] [master 1cd2bfa] Setting version to 0.1
[info]  1 file changed, 1 insertion(+)
[info]  create mode 100644 version.sbt
[info] Reapplying settings...
[info] Set current project to testsbtmultiprojectbintray (in build file:/Users/sdunc4/tmp/testsbtmultiprojectbintray/)
[info] Reapplying settings...
[info] Set current project to testsbtmultiprojectbintray (in build file:/Users/sdunc4/tmp/testsbtmultiprojectbintray/)
[info] Updating {file:/Users/sdunc4/tmp/testsbtmultiprojectbintray/}testsbtmultiprojectbintray...
[info] Resolving jline#jline;2.14.5 ...
[info] Done updating.
[info] :: delivering :: com.stephenduncanjr#testsbtmultiprojectbintray_2.12;0.1 :: 0.1 :: release :: Fri Mar 09 11:42:44 PST 2018
[info] 	delivering ivy file to /Users/sdunc4/tmp/testsbtmultiprojectbintray/target/scala-2.12/ivy-0.1.xml
[info] Updating {file:/Users/sdunc4/tmp/testsbtmultiprojectbintray/}testsbtmultiprojectbintray-extra...
[info] Packaging /Users/sdunc4/tmp/testsbtmultiprojectbintray/extra/target/scala-2.12/testsbtmultiprojectbintray-extra_2.12-0.1-sources.jar ...
[info] Done packaging.
[info] Wrote /Users/sdunc4/tmp/testsbtmultiprojectbintray/extra/target/scala-2.12/testsbtmultiprojectbintray-extra_2.12-0.1.pom
[info] Resolving jline#jline;2.14.5 ...
[info] Done updating.
[info] :: delivering :: com.stephenduncanjr#testsbtmultiprojectbintray-extra_2.12;0.1 :: 0.1 :: release :: Fri Mar 09 11:42:45 PST 2018
[info] 	delivering ivy file to /Users/sdunc4/tmp/testsbtmultiprojectbintray/extra/target/scala-2.12/ivy-0.1.xml
[info] Packaging /Users/sdunc4/tmp/testsbtmultiprojectbintray/extra/target/scala-2.12/testsbtmultiprojectbintray-extra_2.12-0.1.jar ...
[info] Main Scala API documentation to /Users/sdunc4/tmp/testsbtmultiprojectbintray/extra/target/scala-2.12/api...
[info] Done packaging.
model contains 2 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /Users/sdunc4/tmp/testsbtmultiprojectbintray/extra/target/scala-2.12/testsbtmultiprojectbintray-extra_2.12-0.1-javadoc.jar ...
[info] Done packaging.
[info] 	published testsbtmultiprojectbintray-extra_2.12 to https://api.bintray.com/maven/jrduncans/maven/maven/com/stephenduncanjr/testsbtmultiprojectbintray-extra_2.12/0.1/testsbtmultiprojectbintray-extra_2.12-0.1.pom
[info] 	published testsbtmultiprojectbintray-extra_2.12 to https://api.bintray.com/maven/jrduncans/maven/maven/com/stephenduncanjr/testsbtmultiprojectbintray-extra_2.12/0.1/testsbtmultiprojectbintray-extra_2.12-0.1.jar
[info] 	published testsbtmultiprojectbintray-extra_2.12 to https://api.bintray.com/maven/jrduncans/maven/maven/com/stephenduncanjr/testsbtmultiprojectbintray-extra_2.12/0.1/testsbtmultiprojectbintray-extra_2.12-0.1-sources.jar
[info] 	published testsbtmultiprojectbintray-extra_2.12 to https://api.bintray.com/maven/jrduncans/maven/maven/com/stephenduncanjr/testsbtmultiprojectbintray-extra_2.12/0.1/testsbtmultiprojectbintray-extra_2.12-0.1-javadoc.jar
[info] jrduncans/testsbtmultiprojectbintray@0.1 was released
java.lang.RuntimeException: was not able to find or create a package for jrduncans in Repo(jrduncans,maven) named testsbtmultiprojectbintray
	at scala.sys.package$.error(package.scala:27)
	at bintray.BintrayRepo.ensurePackage(BintrayRepo.scala:49)
	at bintray.BintrayPlugin$$anonfun$ensurePackageTask$1.apply(BintrayPlugin.scala:164)
	at bintray.BintrayPlugin$$anonfun$ensurePackageTask$1.apply(BintrayPlugin.scala:159)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (testsbtmultiprojectbintray-core/*:bintrayEnsureBintrayPackageExists) was not able to find or create a package for jrduncans in Repo(jrduncans,maven) named testsbtmultiprojectbintray
[error] Total time: 8 s, completed Mar 9, 2018 11:42:52 AM

**Comment by 2m** [comment] 2018-03-27 12:09
Possible duplicate of #38.

**Closed** 2021-02-27 19:38 UTC
