### ISSUE TITLE
Problems publishing (and releasing) to bintray

### ISSUE THREAD

**Issue by NicolasRouquette** [sbt/sbt-bintray#91] opened 2016-08-22 06:13 UTC
I've developed an SBT plugin that we've been using internally at JPL for a while.
I configured a Travis CI job to build this plugin.
However, I'm really struggling with the bintray-sbt configuration to publish it.

The sbt plugin is here on github: 
https://github.com/JPL-IMCE/imce.sbt.plugin/tree/imce.sbt.plugin-6

The Travis CI job is here:
https://travis-ci.org/JPL-IMCE/imce.sbt.plugin

I couldn't get travis ci to publish to binary directly so I tried bintray-sbt.
However, it is really difficult to tell what's going on & what it is trying to do.

With 'publishSigned', I get this kind of error:
(see for example: https://travis-ci.org/JPL-IMCE/imce.sbt.plugin/builds/154060867)

```
{"message":"This resource requires authentication"}
java.lang.RuntimeException: error uploading to default/imce-sbt-plugin/scala_2.10/sbt_0.13/3.9/docs/imce-sbt-plugin-javadoc.jar: {"message":"This resource requires authentication"}
    at bintray.BintrayIvyRepository.put(Resolver.scala:59)
    at org.apache.ivy.plugins.resolver.RepositoryResolver.put(RepositoryResolver.java:234)
    at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
    at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:381)
    at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:380)
```

With 'publish', I get a different error:

```
java.lang.RuntimeException: The configured repo MUST be a maven repo, but was: Raw(Bintray-Sbt-Publish-jpl-imce-gov.nasa.jpl.imce-imce-sbt-plugin)
    at scala.sys.package$.error(package.scala:27)
    at aether.AetherPlugin$$anonfun$1.applyOrElse(Plugin.scala:97)
    at aether.AetherPlugin$$anonfun$1.applyOrElse(Plugin.scala:95)
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
    at scala.Option.collect(Option.scala:250)
    at aether.AetherPlugin$class.deployIt(Plugin.scala:95)
    at aether.AetherPlugin$.deployIt(Plugin.scala:26)
```

Any suggestions?

**Comment by FlorianKirmaier** [comment] 2016-09-01 12:36
I've got the same error. It started several weeks ago. Probably Bintray changed something on their api.
I tried to fork bintray-sbt and solve the issue, but i was not successful.
At the moment, I'm publishing to somewhere else as an workaround.

As far as i know, the problem only occurs when the following setting is defined:
```
publishMavenStyle := true,
```

**Comment by NicolasRouquette** [comment] 2016-09-01 16:05
I really wanted to publish to & resolve from bintray because it supports a staging-like 2-phase upload (resolvable privately to developer) and publish (resolvable publicly) similar to Nexus Pro (see: https://github.com/xerial/sbt-sonatype/blob/master/workflow.md)

I tried the JFrog CLI (works well) but then realized that in fact SBT's Resolver.bintrayRepo("<org>", "<repo>") is sufficient. 

With this, remember that `sbt publish` corresponds to bintray upload.
Uploaded artifacts are privately resolvable (i.e. need SBT credentials for bintray)

Then, you can use the JFrog CLI (`jfrog bt vp <org>/<repo>/<package>/<version>`) to publish (in bintray lingo) all the files uploaded to a specific version of a package. After that, the artifact is resolvable publicly without credentials.

This is what I've used for several projects (see: https://github.com/TIWG, https://github.com/JPL-IMCE)

**Comment by 2m** [comment] 2018-03-27 11:13
Sbt setting application order and some concurrency issues have been fixed since, which might render this issue obsolete. Closing this for now. If the problem is still there, please feel free to open another ticket.

**Closed by 2m** 2018-03-27 11:13 UTC
