### ISSUE TITLE
Publish artifact that matches a "Maven Central"-style named package

### ISSUE THREAD

**Issue by schmmd** [sbt/sbt-bintray#56] opened 2015-05-05 15:21 UTC
Hi, I asked [a question on SO yesterday](http://stackoverflow.com/questions/30034297/how-do-i-publish-an-artifact-to-bintray-using-sbt-so-it-matches-the-artifact-alr).  I got a not-so-helpful response from BinTray on this topic, but it made me wonder if `bintray-sbt` is getting in my way here.  Is it possible to use `bintray-sbt` to publish an artifact named `org.allenai.common:common-core_2.11` to BinTray?  When I tried that, it was renamed to `org-allenai-common=common-core_2.11`.

**Comment by jvican** [comment] 2017-06-25 19:07
@schmmd Did you get around this? If so, can you explain how? Otherwise, I'll just close the issue since there's no way we can reproduce.

**Comment by 2m** [comment] 2018-03-27 10:56
Closing the ticket due to the lack of additional information. Feel free to create a new ticket if the problem is still there.

**Closed by 2m** 2018-03-27 10:56 UTC
